[build]
builder = "nixpacks"
ignore = ["Dockerfile", "docker-compose.yml", ".dockerignore", "docker/"]

[build]
builder = "nixpacks"
ignore = ["Dockerfile", "docker-compose.yml", ".dockerignore", "docker/"]